module.exports = {
    url: 'http://localhost:3000/#/',
    elements: {
        app: '#pageWrap',
        menuButton: 'div:nth-child(3) > div > button',
        dropMenu: '[class="bm-menu"]',
        xButton: 'div:nth-child(2) > div > button',
        dropDownHome: 'p[name="homeOption"]',
        dropDownEw: 'p[name="enterOption"]',
        dropDownModify: 'p[name="modifyOption"]',
        dropDownCancel: 'p[name="cancelOption"]',
        tileBar: '[class="titleBar"]',
        enterWantedName: 'ul > li:nth-child(1) > h3',
        enterWantedDesc: 'ul:nth-child(2) > li',
        modifyWantedName: 'li:nth-child(3) > h3',
        modifyWantedDesc: 'ul:nth-child(4) > li',
        cancelWantedName: 'li:nth-child(5) > h3',
        cancelWantedDesc: 'ul:nth-child(6) > li',
        versionNumber: 'h6',
        warrantIdHdr: '[name="widHeader"]',
        warrantId: '[name="widInput"]',
        headerHdr: '[name="hdrHeader"]',
        header: '[name="hdrInput"]',
        mkeHdr: '[name="mkeHeader"]',
        mke: '[name="mkeInput"]',
        oriHdr: '[name="oriHeader"]',
        ori: '[name="oriInput"]',
        nameHdr: '[name="namHeader"]',
        name: '[name="namInput"]',
        sexHdr: '[name="sexHeader"]',
        sex: '[name="sexInput"]',
        raceHdr: '[name="racHeader"]',
        race: '[name="racInput"]',
        heightHdr: '[name="hgtHeader"]',
        height: '[name="hgtInput"]',
        weightHdr: '[name="wgtHeader"]',
        weight: '[name="wgtInput"]',
        hairHdr: '[name="haiHeader"]',
        hair: '[name="haiInput"]',
        offenseHdr: '[name="offHeader"]',
        offense: '[name="offInput"]',
        dowHdr: '[name="dowHeader"]',
        dow: '[name="dowInput"]',
        dLicenseHdr: '[name="olnHeader"]',
        dLicense: '[name="olnInput"]',
        dlStateHdr: '[name="olsHeader"]',
        dlState: '[name="olsInput"]',
        dlExpHdr: '[name="oldHeader"]',
        dlExp: '[name="oldInput"]',
        licPlateHdr: '[name="licHeader"]',
        licPlate: '[name="licInput"]',
        licStateHdr: '[name="lisHeader"]',
        licState: '[name="lisInput"]',
        licExpHdr: '[name="lidHeader"]',
        licExp: '[name="lidInput"]',
        saveBtn: 'button#saveBtn',
        clearBtn: 'button#clearBtn',
        results: 'td[class="results"]',
        resCancelHdr: '[name="resHeader]',
        resCancel: '[name="resInput"]',
        dateCancelHdr: '[name="datHeader"]',
        dateCancel: '[name="datInput"]',
        


        

    },
}